# Generated by Django 2.2.4 on 2019-12-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('pnum', models.IntegerField()),
                ('sumprice', models.CharField(max_length=64)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pdname', models.CharField(max_length=128)),
                ('pdprice', models.FloatField()),
                ('discount', models.FloatField()),
                ('pdImage', models.TextField()),
                ('pdInfo', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='Shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PayCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carttopay', to='Shop.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernum', models.CharField(max_length=32)),
                ('allprice', models.FloatField()),
                ('allpnum', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='Shop.Product')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_order', to='user.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cat', to='Shop.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_cat', to='user.UserInfo'),
        ),
    ]
