# Generated by Django 2.2.1 on 2019-09-18 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('identity', models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='学生', max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=128)),
                ('get_name', models.CharField(max_length=128)),
                ('get_phone', models.CharField(max_length=128)),
                ('get_code', models.CharField(max_length=128)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_address', to='user.UserInfo')),
            ],
        ),
    ]
