# Generated by Django 2.2.1 on 2019-10-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128)),
                ('packname', models.CharField(max_length=255, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('total', models.CharField(max_length=128)),
                ('surplus', models.CharField(max_length=128)),
            ],
        ),
    ]
