# Generated by Django 2.2.1 on 2019-09-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('addtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('root', models.IntegerField()),
            ],
        ),
    ]
