# Generated by Django 2.2.4 on 2019-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('essay_id', models.CharField(blank=True, max_length=60, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField(blank=True)),
                ('essay_id', models.IntegerField(blank=True, null=True)),
                ('author_id', models.IntegerField()),
                ('commit_time', models.DateTimeField(auto_now_add=True)),
                ('start_ocr_time', models.DateTimeField(blank=True, null=True)),
                ('finish_ocr_time', models.DateTimeField(blank=True, null=True)),
                ('start_check_time', models.DateTimeField(blank=True, null=True)),
                ('finish_check_time', models.DateTimeField(blank=True, null=True)),
                ('start_correct_time', models.DateTimeField(blank=True, null=True)),
                ('finish_correct_time', models.DateTimeField(blank=True, null=True)),
                ('start_verify_time', models.DateTimeField(blank=True, null=True)),
                ('finish_verify_time', models.DateTimeField(blank=True, null=True)),
                ('correct_mode', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=32, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(max_length=32)),
                ('essay_text', models.TextField(blank=True, null=True)),
                ('essay_image', models.ImageField(blank=True, null=True, upload_to='imgs')),
                ('statistics', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('system_id', 'essay_id')},
            },
        ),
    ]
